#!/usr/bin/env sh
set -eu

# Staging-only entrypoint. Fail BEFORE migrations and HTTP startup.
deny() {
    printf '%s\n' "MCP isolated staging guard: BLOCKED ($1)" >&2
    exit 42
}

[ "${CANOVIA_STAGING_ISOLATED:-}" = "true" ] || deny "staging marker missing"
[ "${APP_ENV:-}" = "staging" ] || deny "APP_ENV must equal staging"
[ "${APP_DEBUG:-}" = "false" ] || deny "debug must be disabled"

# Database mode is explicit: retain disposable SQLite by default, or use
# ONLY the pre-created, independent Free Render staging PostgreSQL instance.
# Reject all unapproved Aiven/live database hosts before ANY migration.
[ -z "${DATABASE_URL:-}" ] || deny "DATABASE_URL unsupported"
[ -z "${PGPASSWORD:-}" ] || deny "PGPASSWORD unsupported"
[ -z "${PGHOST:-}" ] || deny "PGHOST unsupported"
[ -z "${PGDATABASE:-}" ] || deny "PGDATABASE unsupported"
[ -z "${MYSQL_ATTR_SSL_CA:-}" ] || deny "MySQL CA unsupported"
[ -z "${DB_HOST:-}" ] || deny "DB_HOST override forbidden"
[ -z "${DB_USERNAME:-}" ] || deny "DB_USERNAME override forbidden"
[ -z "${DB_PASSWORD:-}" ] || deny "DB_PASSWORD override forbidden"
[ -z "${DB_SOCKET:-}" ] || deny "DB_SOCKET override forbidden"

case "${CANOVIA_STAGING_DB_MODE:-sqlite}" in
    sqlite)
        [ "${DB_CONNECTION:-}" = "sqlite" ] || deny "SQLite driver required"
        [ "${DB_DATABASE:-}" = "/var/www/html/storage/app/staging/mcp.sqlite" ] \
            || deny "SQLite database path mismatch"
        [ -z "${DB_URL:-}" ] || deny "external URL forbidden for SQLite"
        # A partially applied Postgres cutover must never silently boot
        # the old SQLite DB with an unrelated Render username reference.
        [ -z "${CANOVIA_STAGING_POSTGRES_USER:-}" ] \
            || deny "staging Postgres user set while using SQLite"
        ;;
    render_postgres)
        [ "${DB_CONNECTION:-}" = "pgsql" ] || deny "PostgreSQL driver required"
        [ "${DB_DATABASE:-}" = "canovia_mcp_staging_db" ] \
            || deny "Postgres database name mismatch"
        [ "${CANOVIA_STAGING_POSTGRES_ID:-}" = "dpg-db43rbbncjis73bmigi0-a" ] \
            || deny "Postgres resource ID mismatch"

        # Database URL is read as a process environment variable, never
        # logged or accepted from user input; compare immutable host and DB
        # name to the exact Render staging instance. Internal Render only.
        [ -n "${DB_URL:-}" ] || deny "staging PostgreSQL URL missing"
        # Username may be generated by Render and is not part of the
        # public database metadata. Match the URL to a separate Render-
        # managed fromDatabase: {property: user} value, never a guess.
        [ -n "${CANOVIA_STAGING_POSTGRES_USER:-}" ] \
            || deny "staging Postgres user reference missing"
        php -r '
            $raw = getenv("DB_URL");
            $p = is_string($raw) ? parse_url($raw) : false;
            if (!is_array($p)
                || !in_array($p["scheme"] ?? "", ["postgres", "postgresql"], true)
                || ($p["host"] ?? "") !== "dpg-db43rbbncjis73bmigi0-a"
                || !preg_match("/\\A[a-z][a-z0-9_]{2,127}\\z/D", getenv("CANOVIA_STAGING_POSTGRES_USER") ?: "")
                || ($p["user"] ?? "") !== getenv("CANOVIA_STAGING_POSTGRES_USER")
                || ($p["path"] ?? "") !== "/canovia_mcp_staging_db"
                || ($p["port"] ?? 5432) !== 5432
                || !isset($p["pass"]) || strlen($p["pass"]) < 8
                || isset($p["query"]) || isset($p["fragment"])) {
                exit(42);
            }
        ' || deny "Postgres URL fails pinned staging resource validation"
        ;;
    *) deny "unsupported staging database mode" ;;
esac

[ "${SESSION_DRIVER:-}" = "file" ] || deny "local sessions required"
[ "${CACHE_STORE:-}" = "file" ] || deny "local cache required"
[ "${QUEUE_CONNECTION:-}" = "sync" ] || deny "background workers forbidden"
[ "${MAIL_MAILER:-}" = "log" ] || deny "outbound email forbidden"
[ -z "${SESSION_DOMAIN:-}" ] || deny "cookie domain must be unset"
[ "${SESSION_COOKIE:-}" = "canovia_mcp_staging_session" ] \
    || deny "isolated session cookie required"

# Exact HTTPS onrender staging hostname, no path/query/fragment/credentials.
case "${APP_URL:-}" in
    https://*staging*.onrender.com) ;;
    *) deny "APP_URL must be an isolated staging onrender.com host" ;;
esac
host="${APP_URL#https://}"
case "$host" in
    *"/"*|*"?"*|*"#"*|*"@"*|*":"*|*" "*|*".."*|*"_"*)
        deny "unsafe staging hostname" ;;
    pacekeeper-d3mm.onrender.com|app.canovia.com|canovia.com)
        deny "production hostname" ;;
esac
# Avoid accepting uppercase, shell special characters or arbitrary host text.
if ! printf '%s\n' "$host" | grep -Eq '^[a-z0-9-]*staging[a-z0-9-]*\.onrender\.com$'; then
    deny "unexpected staging hostname"
fi

# Render generateValue is not a valid Laravel APP_KEY on its own.
# Supply an independently generated base64:<44 chars> key.
case "${APP_KEY:-}" in
    base64:????????????????????????????????????????????) ;;
    *) deny "separate base64 Laravel APP_KEY required" ;;
esac

# Never inherit production integrations, mail, webhook or payment secrets.
for name in GITHUB_READ_TOKEN GITHUB_APP_ID GITHUB_APP_PRIVATE_KEY \
    GITHUB_APP_PRIVATE_KEY_BASE64 GITHUB_APP_WEBHOOK_SECRET \
    GITHUB_TOKEN OPENAI_API_KEY ANTHROPIC_API_KEY \
    STRIPE_SECRET STRIPE_WEBHOOK_SECRET AWS_ACCESS_KEY_ID \
    AWS_SECRET_ACCESS_KEY RESEND_API_KEY; do
    if [ -n "$(printenv "$name" 2>/dev/null || true)" ]; then
        deny "production integration secrets forbidden"
    fi
done

# Real OAuth and MCP capabilities are separately gated in Canovia code.
# Before explicit staging testing approval, even synthetic MCP is OFF.
if [ "${CANOVIA_MCP_TOOLS_ENABLED:-false}" != "false" ]; then
    [ "${CANOVIA_STAGING_MCP_EXPLICITLY_APPROVED:-false}" = "true" ] \
        || deny "MCP tools require separate staging approval"
fi

# Initially only /up is accessible via the Laravel staging middleware.
case "${CANOVIA_STAGING_WEB_ACCESS_ENABLED:-false}" in
    false|true) ;;
    *) deny "invalid staging public-access switch" ;;
esac
case "${CANOVIA_STAGING_WEB_ACCESS_EXPLICITLY_APPROVED:-false}" in
    false|true) ;;
    *) deny "invalid staging public-access approval" ;;
esac
# Merely switching on web access must NEVER expose login/OAuth/MCP.
# A separate operator approval and a pinned durable staging DB are required.
if [ "${CANOVIA_STAGING_WEB_ACCESS_ENABLED:-false}" = "true" ]; then
    [ "${CANOVIA_STAGING_WEB_ACCESS_EXPLICITLY_APPROVED:-false}" = "true" ] \
        || deny "staging public web requires independent approval"
    [ "${CANOVIA_STAGING_DB_MODE:-sqlite}" = "render_postgres" ] \
        || deny "staging public web requires pinned PostgreSQL"
fi

# A synthetic actor can be provisioned during one deliberately armed
# staging restart. This is NOT a Web endpoint or a production seed.
case "${CANOVIA_STAGING_SYNTHETIC_OWNER_BOOTSTRAP_ON_START:-false}" in
    false|true) ;;
    *) deny "invalid synthetic owner startup switch" ;;
esac
if [ "${CANOVIA_STAGING_SYNTHETIC_OWNER_BOOTSTRAP_ON_START:-false}" = "true" ]; then
    [ "${CANOVIA_STAGING_DB_MODE:-sqlite}" = "render_postgres" ] \
        || deny "synthetic owner startup requires pinned PostgreSQL"
    [ "${CANOVIA_STAGING_WEB_ACCESS_ENABLED:-false}" = "false" ] \
        || deny "synthetic owner startup requires closed Web"
    [ "${CANOVIA_STAGING_WEB_ACCESS_EXPLICITLY_APPROVED:-false}" = "false" ] \
        || deny "synthetic owner startup requires no public approval"
    [ "${CANOVIA_STAGING_ALLOW_SYNTHETIC_OWNER_BOOTSTRAP:-false}" = "true" ] \
        || deny "synthetic owner startup requires separate bootstrap approval"
    [ -n "${CANOVIA_STAGING_SYNTHETIC_OWNER_PASSWORD:-}" ] \
        || deny "synthetic owner startup requires private password"
    for name in CANOVIA_MCP_DISCOVERY_ENABLED \
        CANOVIA_MCP_TOKEN_INTROSPECTION_ENABLED \
        CANOVIA_MCP_ACCOUNT_LINK_ENABLED \
        CANOVIA_MCP_PLAN_CONSENT_ENABLED \
        CANOVIA_MCP_DELEGATED_POLICY_ENABLED \
        CANOVIA_MCP_TOOLS_ENABLED; do
        [ "$(printenv "$name" 2>/dev/null || true)" != "true" ] \
            || deny "synthetic owner startup requires MCP gates closed"
    done
fi

# The optional private Plan/Task fixture requires the independently
# approved synthetic owner bootstrap in the same closed staging boot.
# Neither the user nor the Plan is created by merely deploying this code.
case "${CANOVIA_STAGING_SYNTHETIC_PLAN_FIXTURE_ON_START:-false}" in
    false|true) ;;
    *) deny "invalid synthetic Plan fixture startup switch" ;;
esac
if [ "${CANOVIA_STAGING_SYNTHETIC_PLAN_FIXTURE_ON_START:-false}" = "true" ]; then
    [ "${CANOVIA_STAGING_SYNTHETIC_OWNER_BOOTSTRAP_ON_START:-false}" = "true" ] \
        || deny "synthetic Plan fixture requires synthetic owner bootstrap"
    [ "${CANOVIA_STAGING_DB_MODE:-sqlite}" = "render_postgres" ] \
        || deny "synthetic Plan fixture requires pinned PostgreSQL"
    [ "${CANOVIA_STAGING_WEB_ACCESS_ENABLED:-false}" = "false" ] \
        || deny "synthetic Plan fixture requires closed Web"
    [ "${CANOVIA_STAGING_WEB_ACCESS_EXPLICITLY_APPROVED:-false}" = "false" ] \
        || deny "synthetic Plan fixture requires no public approval"
    [ "${CANOVIA_MCP_TOOLS_ENABLED:-false}" = "false" ] \
        || deny "synthetic Plan fixture requires MCP tools closed"
fi

if [ "${1:-}" = "--check-only" ]; then
    printf '%s\n' "MCP isolated staging guard: PASS (config only; no DB/network changes)"
    exit 0
fi
[ "$#" -eq 0 ] || deny "unsupported arguments"

cd /var/www/html
# Never print the private DB URL, password, or connection exception.
# This operator-visible mode marker is not a DB connectivity assertion.
printf '%s\n' "MCP isolated staging startup: configured database mode=${CANOVIA_STAGING_DB_MODE:-sqlite} (connection not yet verified)"
# Production's standard Nginx serves /health and static assets directly,
# bypassing Laravel middleware. Override it for the default-closed stage
# so only Laravel /up is reachable. A separately approved, pinned-DB
# stage may retain standard Nginx for future protected OAuth testing.
if [ "${CANOVIA_STAGING_WEB_ACCESS_ENABLED:-false}" = "false" ]; then
    cp docker/nginx-mcp-staging-closed.conf /etc/nginx/nginx.conf
    nginx -t >/dev/null 2>&1 || deny "closed staging Nginx configuration invalid"
fi

if [ "${CANOVIA_STAGING_DB_MODE:-sqlite}" = "sqlite" ]; then
    mkdir -p storage/app/staging
    touch storage/app/staging/mcp.sqlite
    chown -R www-data:www-data storage/app/staging
fi

# Production boot script runs migrations only AFTER staging DB guard.
exec ./docker/render-start.sh
