<?php

return [
    [
        'version' => 'v41.15',
        'date' => '2026-09-27',
        'title' => 'Canoviaが知っていることを、そのまま会話へ',
        'summary' => 'Goal Context・Plan・Task・EvidenceなどCanoviaが既に持つ文脈を使って相談できるPremium Companionを追加しました。変更提案は人が確認してから反映し、現在画面のContextや未解決の続きも自動で引き継ぎます。',
        'highlights' => [
            'Canovia Companionをautomatic_ai_executionとは別のFeatureKeyとして追加し、Premium Coreの独立Capabilityとして扱います。',
            '会話はglobal / Plan / Taskの3種類のContext scopeを持ち、相談したい範囲を固定できます。',
            'Native AIへは選択中Plan・Task、Goal Context、Recent Evidence最大6件、Inbox未整理件数、Current Screen、直近会話最大12件だけを渡し、全DB履歴を毎回送信しません。',
            'AIが提案できる変更はTask追加・Task変更・Plan変更・Goal Context Fact・未来メモ・InboxのCandidateに限定します。',
            'AIがpayloadへPlan ID・Task ID・User ID等を書いても破棄し、対象はCanovia側のselected contextから決定します。',
            'Mutation Candidateは画面上で確認待ちとして表示し、実際に反映される項目と、安全上反映しない項目を分けて確認できます。',
            '「この内容を反映する」を押した場合だけtype別Validator・所有権確認・transactionを通して更新し、見送りも選べます。',
            'Taskのprogress_percentやdone / cancelledはCompanionから変更せず、実行結果やEvidenceと計画変更を混同しません。',
            'Planの公開設定・共同設定・見た目設定もCompanion Candidateから変更しません。',
            '反映時はapply_request_id・対象ID・before / after・blocked fieldsを保存し、二重送信でもmutationを重複させません。',
            'Goal Context FactはAI由来を保持したまま、人が確認した時だけconfirmed Factとして保存します。',
            'Companion conversationはrequest_idで二重送信を吸収し、同じ送信からNative AI応答やCandidateを重複生成しません。',
            'Native AIが一時失敗した場合もUser messageとrequest_idを保持し、同じ会話を重複させず再試行できます。',
            '各画面右下のLauncherはCurrent ScreenからPlan / Taskを自動判定し、毎回Context selectorへ戻らず対応するConversationを直接開きます。',
            'TaskとGuided Executionは同じTask conversationを継続し、Guided Executionから入った場合は最新EvidenceもContextへ含めます。',
            'Roadmapでは現在選択中Planを引き継ぎ、Inboxでは各Itemの「Companionで整理」からその入力内容を固有Contextとして相談できます。',
            '同じContextは既存Threadを再利用し、Step 1で作成済みのlegacy Threadも継続します。Inbox Itemだけはgeneric Plan conversationと分離します。',
            'Conversationへ移動した後も元画面のsource path / routeを保持し、AIへ渡すCurrent ScreenがCompanion自身へ置き換わらないようにしました。',
            '/companion の手動Context selectorは、別対象やCanovia全体について明示的に相談したい場合のfallbackとして残します。',
            '会話を開くと、確認待ちCandidate・前回会話後の新Evidence・Known Unknown・次Action未整理から最大3件だけを「続き」として提示します。',
            'Continuityは既存Canovia stateから毎回計算し、Candidate確認・Evidence後のreply・Unknown解決・next_action設定に合わせて自動的に消えます。',
            '前回Assistant reply後のEvidenceだけをfollow-up対象にするため、一度整理したEvidenceを何度も同じ続きとして出しません。',
            '確認待ちCandidateは会話一覧にも件数を表示し、Native AIへもpending状態を渡します。同一type・同一payloadのpending Candidateはserver-sideでも重複保存しません。',
            'Continuity表示だけではAIを呼ばず、Messageも自動生成しません。「この続きを相談」を人が押した場合だけ既存Native conversationを実行します。',
            'Push通知やProactive notificationはStep 4では導入せず、実利用データを見て別バージョンで判断します。',
            'Companionはメイン4タブへ追加せず、公開時だけ各画面右下の小型Launcherから開けるpersistent utilityとして配置します。',
            'FreeでもGoal Discovery・Plan・Inbox・Guided Executionなど既存のGoal達成経路は維持し、Companionは文脈整理・判断・転記の摩擦を減らすPremium価値とします。',
        ],
        'tip' => '今見ているContextだけでなく、確認待ちの変更・新しいEvidence・まだ分からないことも続きとして拾います。必要な時だけ相談を再開でき、AIが勝手に会話や変更を増やすことはありません。',
    ],
    [
        'version' => 'v41.14',
        'date' => '2026-09-27',
        'title' => '計画を作る前に、Canoviaが現在地を理解する',
        'summary' => 'Goal Context・Adaptive Goal Discovery・Guided Executionに加え、未知Goalの実利用から専用Tool候補を観測するGoal Pattern Demandを追加しました。新しい入力を求めず、既存の現在地・Unknown・実行・振り返りから需要を読み取ります。',
        'highlights' => [
            'Plan作成時にGoal Contextを自動生成し、既存Planも必要になった時点で安全にlazy生成します。',
            'Goal Context Factはconfirmed / candidate / unknown / supersededを分離し、Native AIの推測をそのまま事実扱いしません。',
            '現在地の把握度はAIの自己評価ではなく、Desired State・Current State・Signal・Constraint・Driver / MeasurementのCoverageから決定論的に計算します。',
            'AI Plan BuilderへConfirmed Facts・Unconfirmed Hints・Known Unknownsを渡し、確認済み情報の聞き直しとUnknownの推測補完を避けます。',
            '現在地不足が重要な場合、長期計画を無理に作らず、測る・観察する・記録するMeasurement Taskを初期Planへ入れられる方針にしました。',
            'Plan BuilderではCanoviaが現在どこまで理解できているかをPreviewできます。',
            'Plan作成の初手は詳細フォームではなく「どうなりたい？」だけにし、Planを作る前からGoal Contextを育てます。',
            '回答方法は先に選ばせず、タップ回答・文章回答・スキップの使われ方からQuick / conversational / compact表示へ自然に適応します。',
            '質問を飛ばすユーザーには仮Planを前へ出し、分からない部分を無理に入力させません。',
            'Readinessが70点以上でも、Desired State・Current State・Success Signalが揃わなければHIGHにしません。',
            '従来の詳細Planフォームはmanual fallbackとして残しています。',
            '商談・練習・面接・運動などの現実世界Taskでは、専用ToolがなければGuided ExecutionをPrimary Actionとして提案します。',
            'Guided Executionでは実行前に目的・意識点・観測点を決めますが、この時点ではEvidenceやWorkSessionを作りません。',
            '実行後のReflectionを確定した時だけTask Evidenceを保存し、自己申告の構造化度に応じてconfidence 0.55〜0.70を付けます。',
            'Guided ReflectionだけでTask Progressは自動変更せず、Timerも自動開始しません。',
            '実装・調査・読書など集中作業では従来どおりTimer fallbackを維持し、専用Toolがある場合は必ずそちらを優先します。',
            'Goal ContextとGuided Executionを別のDemand Logへ複製せず、既存データをSource of TruthとしてGoal Pattern Demandを集計します。',
            '営業・スポーツ・運動・キャリア・学習・開発などのGoal領域ごとに、利用Identity数・Guided Execution回数・反復Task・Measurement Unknownを確認できます。',
            'Opportunity Scoreはcross-user demandを最も重くし、1人の反復利用だけで専用Tool候補を過大評価しない設計です。',
            'Current State・Success Signal・Constraint・Measurement・入力スタイルも構造化された種類だけを集計し、自由記述本文はTool需要画面へ表示しません。',
            'Goal Pattern Demandは観測専用で、AIやScoreが新Tool・課金Feature・Entitlementを自動作成または公開することはありません。',
        ],
        'tip' => '未知の目標はまず汎用伴走で支援し、同じ需要が複数人・複数回で現れた領域だけを専用Tool候補として観測します。Tool化は実データを見て人が判断します。',
    ],
    [
        'version' => 'v41.13',
        'date' => '2026-09-26',
        'title' => '次の行動は1つに。新しい情報はInboxへ',
        'summary' => 'Taskに合う実行方法がある場合はそのActionだけをPrimaryにし、TimerはFallbackへ整理しました。あわせてメインナビの「今日」をInboxへ置き換え、テキスト・URL・画像・PDFを分類前のままCanoviaへ渡せる共通入口を追加しました。',
        'highlights' => [
            'Study Activity / AI演習 / Career / 制作ファイル / 関連資料をTaskごとのPrimary Actionとして共通Policyで選びます。',
            '専用ToolがあるTaskでは補助Timerを並べず、専用Toolがない場合だけTimerをPrimary Fallbackにします。',
            'Study FocusやTask一覧など、Current Taskと重複していた実行CTA・表示を整理しました。',
            'メインナビを Home / Inbox / Roadmap / Timeline に変更し、旧「今日」は互換Routeとして残します。',
            'Inboxはテキスト・URL・画像・スクリーンショット・PDFを、整理先を決める前の状態で保存できます。',
            'Inboxのファイルはprivate storageへ保存し、本人だけが閲覧できます。',
            'Recall Candidate・Career Capture・Planへ未反映のWorkSessionをコピーせずInboxから横断確認できます。',
            'PremiumではInbox内容から行き先候補・理由・確信度を提案できますが、AIはPlan / Task IDを決めず、人が確認してから確定します。',
            'Freeでも手動整理ができ、Future Memo / Career Capture / Task Evidence / 対応Resourceへ接続できます。RecallのCandidate抽出だけはAutomatic AIを使います。',
            'Guideをv2へ更新し、旧「今日」中心の説明をHome / Inbox / Timer fallback / AI演習 / Recall中心へ組み替えました。',
        ],
        'tip' => '今やるTaskはホーム、外から入ってくる情報はInbox、先を見るならロードマップ、過去を振り返るならタイムライン。InboxのAI提案も確定ではなく、最後は人が整理先を決めます。',
    ],
    [
        'version' => 'v41.12',
        'date' => '2026-09-26',
        'title' => '教材からRecallカードを、安全に作る',
        'summary' => '参考書の写真・スクリーンショット・PDF・貼り付けテキストをNative AIで読み取り、Recallカード候補を作れるようにしました。AI出力は直接Deckへ入れず、根拠と信頼度を見ながら人が編集・選択した候補だけを追加します。',
        'highlights' => [
            '画像・PDFはprivate storageへ保存し、所有権チェック付きの経路からだけ元教材を確認できます。',
            'Responses APIへ画像はinput_image、PDFはinput_fileとして渡し、既存のtext-only Native AI呼び出しはそのまま維持します。',
            'AIは最大30件のCandidateを生成し、front / back / note / tags / source excerpt / confidenceを保持します。',
            'Candidateはpendingで隔離され、AIが自動でRecall Deckへ追加する経路はありません。',
            'Review画面でfront・back・noteを修正し、選択したCandidateだけ一括PromoteまたはRejectできます。',
            'Promote時もDeck側のfingerprintを再計算し、既存カードと同一なら重複作成せず再利用します。',
            'Recall本体と手動カード追加はFreeでも成立し、教材からの自動抽出だけAutomatic AI Execution配下に置きます。',
        ],
        'tip' => '参考書全体を一度に渡すより、覚えたいページだけに絞ると候補品質とAPIコストの両方を改善できます。',
    ],
    [
        'version' => 'v41.11',
        'date' => '2026-09-26',
        'title' => '単語・用語学習を、AI問題生成ではなくRecallへ',
        'summary' => 'Study Activity PolicyでRecallが適切と判断されたTaskを、答えを隠して思い出す永続学習ループへ接続しました。Again / Hard / Good / Easyの自己評価に応じて次回確認間隔を調整し、学習実績はTask Evidenceとして残します。',
        'highlights' => [
            '1 Taskを1つのRecall Deckとして扱い、単語・用語カードを永続保存します。',
            'カードは「表 | 裏」またはタブ区切りで一度に100件まで追加でき、同じTask内の重複カードはfingerprintで防ぎます。',
            'Again / Hard / Good / Easyの4段階で想起結果を記録し、次回due_atを決定論で更新します。',
            'Againは約10分後、Goodは初回1日後・2回目3日後、Easyはより長い間隔へ進めます。',
            'review_request_idで二重送信を吸収し、同じレビューでrepetitionsやintervalが二重更新されません。',
            'Recall reviewはTask Evidenceへ残しますが、学習時間や自己評価だけを理由にTask進捗を自動加算しません。',
            'repetitions 3回以上かつinterval 7日以上のカードを「定着候補」として表示します。',
        ],
        'tip' => 'V41.11では手動カード追加を正としています。教材・PDF・スクリーンショットからの自動カード生成は、内容確認を挟むCandidate方式で後続実装します。',
    ],
    [
        'version' => 'v41.10',
        'date' => '2026-09-26',
        'title' => '次のTaskだけでなく、次の学び方まで選ぶ',
        'summary' => 'AI演習のTask跨ぎに加えて、Task内容からQuestion Practice / Recall / Resource Studyを選ぶStudy Activity Policyを追加しました。AI演習が最善でない学習では別の方法をPrimaryにし、演習画面では出題・採点・Coverage・学習方法との相性を視覚的に確認できます。',
        'highlights' => [
            'next_step=complete_taskや進捗100%提案はcompletion signalとして扱い、AIだけではTaskを完了できません。',
            '直近2回でscore 85%以上・重大な弱点Signalなしが続いた場合に、CanoviaがTask完了を確定します。',
            '確認が足りない場合はTaskを最大99%に留め、5問目安の「完了前の仕上げ確認」をTask全体から出題します。',
            '仕上げ確認を通過するとdependencyを考慮して次に実行可能なTaskを選び、そのTask内容で新しい演習Strategy / Promptを組み立てます。',
            '採点後画面はNEXT ACTIONとPrimary CTAを主役にし、Task反映用の重複CTAを廃止しました。',
            '強み・弱点・問題別Feedback・評価根拠は「詳しい評価を確認」へ折りたたみ、次の行動を見失いにくくしました。',
            'Task内容からQuestion Practice / Recall / Resource Studyの適合度を判定し、TOEIC単語などではRecallをPrimaryにします。',
            'AI演習には出題内容・採点・Coverage・学習方法との相性をグラフ表示し、実測AI正答率ではない目安であることも明示します。',
        ],
        'tip' => 'AI演習を常に勧めるのではなく、Taskによっては単語帳・教材学習など別の方法を先に選びます。AI演習は必要なときの理解確認として残ります。',
    ],
    [
        'version' => 'v41.9',
        'date' => '2026-09-26',
        'title' => '足りない問題を見つけ、AI生成問題を安全に育てる',
        'summary' => 'Practice DemandをAdminで集計し、Question Bankが不足している試験・重点分野を確認できるようにしました。Native AIが実際に生成した問題はCandidateとして隔離し、人が内容と正答を確認したものだけDraft Question Packへ昇格できます。',
        'highlights' => [
            '演習Session数、要求問題数、Question Bank供給数、AI補完不足数、生成数を期間・exam profile・assembly modeで確認できます。',
            'focus topicは問題数を推定配賦せず、Bank不足を伴ったSession数として需要シグナルを表示します。',
            'Native AI生成問題はQuestion Bankへ直接入れず、pending Candidateとして問題文・回答形式・生成文脈を記録します。',
            '同じCandidateが再生成された場合はfingerprintでまとめ、生成回数と最新需要を更新します。同じDemandの再処理では重複カウントしません。',
            'Candidateの正答・grading_rule・learning metadata・解説はAdminが確認し、既存Question検証を通してDraft Packへ追加します。',
            'Candidateからreview / published / retired Packへの直接昇格は禁止し、既存のDraft → Review → Published境界を維持します。',
        ],
        'tip' => 'CandidateはAIの出力をそのまま正解扱いする仕組みではありません。問題資産へ昇格する前に、人が問題文・選択肢・正答・解説・分類を確認します。',
    ],
    [
        'version' => 'v41.8.2',
        'date' => '2026-09-26',
        'title' => '問題集を先に使い、足りない分だけAIで補う',
        'summary' => 'PremiumのAI演習をHybrid Question Assemblyへ変更し、Question Bankで賄える問題を先に使って不足分だけNative AIで生成するようにしました。演習需要と供給不足も将来の問題集拡充に使える形で記録します。',
        'highlights' => [
            'Question BankのCoverageが一部しかなくても、使える問題を先に選定し、空いた枠だけNative AIへ依頼します。',
            'Question Bankだけで必要数を揃えられる場合はNative AIを呼ばず、待ち時間とAPIコストを抑えます。',
            'Native AIへは既に選定済みのBank問題を伝え、同じ問題・単純な数値差し替えの重複を避けるようにしました。',
            'Hybrid演習の評価では、Bank問題のgrading_ruleをブラウザへ出さずサーバー側だけでNative AIへ渡し、正答基準を維持します。',
            'practice_question_demandsに要求問題数、Bank供給数、生成不足数、生成数、focus_topics、exam profile、Coverageを記録します。',
            'Practice DemandはAP専用ではなく、今後別の資格・学習領域でも同じ需要/供給分析へ使える汎用構造です。',
        ],
        'tip' => 'V41.9ではPractice Demandを管理画面で集計し、どの分野のQuestion Bankを次に増やすべきか判断できるようにします。',
    ],
    [
        'version' => 'v41.8.1',
        'date' => '2026-09-26',
        'title' => 'AI演習の回答欄を、問題の考え方に合わせる',
        'summary' => 'Native AIで選択問題を生成したときも、計算や条件整理が学習診断に重要な問題では、最終回答だけでなく計算過程・思考過程を入力できるようにしました。',
        'highlights' => [
            '各AI生成問題へwork_inputを追加し、none / reasoning / calculationの3種類で入力形式を明示します。',
            '単純な知識確認はchoice-onlyを維持し、すべての問題へ記述欄を強制しません。',
            '条件整理・比較・判断根拠が重要な問題では「考え方・判断理由」のtextareaを表示します。',
            '式・途中値・単位変換などが重要な問題では「計算過程」のtextareaを表示します。',
            'Native AIがtextareaを返し忘れても、work_inputがreasoning / calculationならCanovia側が診断用textareaを補完します。',
            '同じ正規化を外部AIからのJSON読込にも適用し、Native / 外部AIで回答UIの考え方が分かれないようにしました。',
        ],
        'tip' => '思考・計算欄は学習診断用で任意です。本番形式の選択回答はそのまま維持します。',
    ],
    [
        'version' => 'v41.8',
        'date' => '2026-09-25',
        'title' => 'Premiumなら、AI演習のコピペをCanoviaが引き受ける',
        'summary' => 'Freeの外部AI Handoffを残したまま、Premium Coreでは問題生成と回答評価をCanovia内のNative AIで完結できる最初の実行経路を追加しました。',
        'highlights' => [
            'AI Practice本体と外部AIの手動HandoffはFreeのまま維持し、Native AI実行だけをPremium CoreのAutomatic AI Executionへ接続しました。',
            'Question Bankで十分にカバーできない演習では、Premiumは「Canoviaで演習を始める」から問題生成を直接実行できます。',
            'Native AIで生成した問題も既存の回答UI・途中保存・StudyPracticeSession・弱点分析をそのまま利用します。',
            '回答後の評価もPremiumではCanovia内で実行し、結果・Evidence・次Actionまで外部AIとのコピペなしで進められます。',
            'Native AIが一時的に失敗しても回答や学習経路を失わず、従来の外部AI Prompt / JSON Handoffへfallbackします。',
            'Native AI Runへprovider・model・AI Capacity・token使用量・成否を記録し、将来のquotaやコスト制御へ備えます。',
            '同じprepare_request_idの再送ではProviderを再実行せず、二重API呼び出しを防ぎます。',
        ],
        'tip' => 'Native AIはserver-side設定を有効化した環境だけで動きます。V41.8では決済・公開Paywall・AI利用量課金はまだ追加していません。',
    ],
    [
        'version' => 'v41.7',
        'date' => '2026-09-25',
        'title' => '設定とPremium検証を、実運用できる形へ',
        'summary' => '設定画面を共通ハブへ広げ、Canoviaの運営者だけが使える管理導線と、身近なユーザーへPremiumを無償提供して体験を試せる仕組みを追加しました。',
        'highlights' => [
            'ヘッダーの「表示」を「設定」へ変更し、従来のテーマ・アクセント・表示密度を設定内の「表示」として残しました。',
            'Super Adminはサーバー側で指定した1アカウントだけに固定し、一般ユーザーが管理画面URLを知っていてもアクセスできないようにしました。',
            'Super Adminは検証のため全Featureを利用でき、Free / Premiumとして見え方とFeature Accessを一時的に確認できます。',
            '管理者画面から特定ユーザーへPremium Coreを無償付与でき、無期限・30日・90日・任意期限を選べます。',
            '無償Premiumは通常のPremium権利として動作しますが、管理者権限・All Access・AI Capacity Boostは付与しません。',
            '無償Premiumの解除は履歴を削除せず終了時刻を記録し、誰にいつ提供したかを後から確認できる形にしました。',
        ],
        'tip' => 'V41.7では決済やNative AIはまだ追加していません。次の段階でPremium CoreへNative AI Practiceを接続し、課金すると何が楽になるかを実体験として検証します。',
    ],
    [
        'version' => 'v41.5',
        'date' => '2026-09-25',
        'title' => 'Canovia Economyの土台を、課金処理より先に',
        'summary' => 'Freeの核体験を維持したまま、Premium Core・用途別Pack・All Access・AI Capacityを既存Entitlement境界へ接続できるEconomy Foundationを追加しました。',
        'highlights' => [
            'Premium Core / Study / Career / Developer / Creator / All Access / AI Capacity BoostをProduct Catalogとして分離し、Feature codeへ料金プラン名を持ち込まない構造にしました。',
            '決済前でもProduct Grantを手動付与できるprovider-neutralなuser_product_grantsを追加し、将来StoreKitやStripeから同期できる形にしました。',
            'Product Grantは既存FeatureAccessServiceへProductGrantEntitlementResolver経由で流し、Feature Flag・Ownershipとの責務分離を維持します。',
            'AI CapacityはEntitlementと分離し、All AccessでもAI利用量が無制限にならない構造にしました。',
            '料金構成の推薦は生成AIではなく決定論で開始し、Freeのままが適切な場合は正式にFreeを返します。',
            'Admin Economy Inspectorで、Grant・effective Product・Feature access・AI Capacity・推薦理由を開発中に確認できます。',
            'Coinは直接Featureを解放するEntitlement sourceから外し、将来の応援・Gift・自己表現向け別経済として整理しました。',
        ],
        'tip' => 'V41.5では購入・課金・Paywallはまだありません。まず権利と機能の境界を安定させ、Native AIの実装時に実際のPremium価値へ接続します。',
    ],
    [
        'version' => 'v41.4',
        'date' => '2026-09-25',
        'title' => 'AI演習を「難しい」より「本番で役立つ」へ',
        'summary' => '資格試験の本番形式に合わせて問題形式・計算負荷を調整し、1回のミスだけで同じ弱点へ出題が偏らないWeakness Priorityと横断診断を追加しました。',
        'highlights' => [
            'AP科目Aでは4択を基本とし、計算問題も不要に桁数の多い値や面倒な小数計算だけで難易度を上げないよう外部AI用Promptを調整しました。',
            '弱点は単純な誤答回数ではなく、繰り返し確認されたか・誤りの種類・改善コスト・最近その分野をやり過ぎていないかを含めて優先度を決めます。',
            '単発の誤答や軽い計算ミスはすぐ重点弱点へ固定せず、「再確認」として扱い、横断診断を多めに残します。',
            '演習問題を「重点弱点 / 他の弱点・再確認 / 横断診断」に配分し、既知の弱点に隠れた別の弱点も継続して探します。',
            'Canovia Question Bankの問題選定も同じ配分を使い、弱点問題だけを上から並べ続ける選び方から、分野を跨ぐbalanced selectorへ更新しました。',
            'AI評価ではknowledge_gap・concept_gap・calculation_slip・condition_reading等のerror_typeを分け、計算ミスと概念理解不足を同じ重さで扱わないようにしました。',
            '問題ごとのフィードバック画面にも「計算ミス」「概念理解」「原因未確定」などのError Typeを表示します。',
        ],
        'tip' => '弱点補強中でも横断診断を混ぜます。1問ミスした直後に同じ系統だけが続くのではなく、本当に得点改善につながる弱点を優先します。',
    ],
    [
        'version' => 'v41.3',
        'date' => '2026-09-25',
        'title' => '就活を「入力して管理」から「経験を残して次へ」へ',
        'summary' => '就活PlanにCareer Capture Inbox・応募/選考データ・面接予定・面接後Reviewを追加し、スクショやURLを先に投げるだけで後から選考へつなげられる基盤を作りました。',
        'highlights' => [
            'Career Capture Inboxを追加し、求人・応募完了・面接案内などのスクリーンショットまたはURLを、企業名を入力せず先に保存できます。',
            'スクリーンショットは公開URLへ置かず、非公開のDB Payloadとして保存し、Plan閲覧権限を持つユーザーだけが表示できます。',
            'CareerApplication / CareerSelectionEventを追加し、応募先・選考段階・面接予定・結果待ちをTask推測とは別の実データとして扱えるようにしました。',
            '応募データが存在する場合、CAREER PIPELINEはTask推測よりCareerApplicationを優先して表示します。',
            '面接予定前はNEXT INTERVIEW、面接時刻を過ぎて振り返り未完了ならINTERVIEW REVIEW、振り返り後はRESULT WAITINGへSurfaceが切り替わります。',
            'Interview Reviewは固定フォームに閉じず、前回の「次に意識すること」を次回質問へ引き継ぐrule-based Question Serviceを採用しました。',
            '面接振り返り完了と選考結果はTaskに紐づいている場合Native Evidenceとして残しますが、それだけでTask進捗率は変更しません。',
            'Career Capture Serviceを共通入口にして、将来のメール・Calendar・スクショAI解析が同じCaptureモデルへ流れ込めるようにしました。',
        ],
        'tip' => '求人を見つけたら、まずスクショかURLだけCareerへ投げて大丈夫です。入力できない情報を無理に埋める必要はありません。',
    ],
    [
        'version' => 'v41.2',
        'date' => '2026-09-25',
        'title' => 'Planごとに「今必要な画面」が変わるように',
        'summary' => 'カテゴリと現在状況からPlan Hubのカード構成を組み替えるAdaptive Surface Engineを追加し、就活・学習・開発/制作で必要な情報を出し分けられる土台を作りました。',
        'highlights' => [
            'Plan Hubのカードを固定Blade構成から登録済みSurface Moduleへ分離し、必要なカードだけを優先順に表示できるようにしました。',
            'Category Profileで資格学習・就活/キャリア・開発・制作・汎用を判定し、同じSurface Engineからカテゴリ別の初期構成を作ります。',
            '就活・キャリアPlanでは応募/書類・面接/選考・内定/条件確認などをTask内容から段階別に整理するCareer Pipelineを表示します。',
            '面接Taskが存在する間だけInterview Focusを優先表示し、面接Taskがなくなると自動で非表示になります。',
            '資格学習ではStudy Focus、開発・制作では成果物がある場合だけDelivery Focusを表示します。',
            'ロードマップもCategory Profileを共有し、就活なら選考ロードマップ、学習なら学習ロードマップなど文脈に合う見せ方へ切り替えます。',
            '将来AIは登録済みSurface IDの並べ替え/非表示だけを提案できる安全なPolicy契約を追加し、任意HTMLや未知のカードは注入できない構造にしました。',
            '計画作成・編集に「就活・キャリア」カテゴリを追加し、未来メモの就職・将来候補も同カテゴリへ引き継ぎます。',
        ],
        'tip' => '同じPlanでも状況が変わると前面に出るカードが変わります。機能一覧から探すより、Plan Hubで今必要なSurfaceから進めます。',
    ],
    [
        'version' => 'v41.1',
        'date' => '2026-09-24',
        'title' => 'Canoviaが「進んだ事実」をもっと拾えるように',
        'summary' => 'AI演習に加えて、Taskに紐づく制作ファイルの登録・更新と集中タイマーの完了もEvidenceとして記録し、Plan Hubから最近のEvidenceを確認できるようにしました。',
        'highlights' => [
            'Taskに紐づけた制作ファイルの登録・更新をartifact Evidenceとして自動記録します。',
            '集中タイマーの完了・中断もactivity Evidenceとして残しますが、時間だけでTask進捗は変更しません。',
            'オフラインで記録した集中タイマーも接続復帰後に同じEvidenceへ統合します。',
            'Plan HubのCURRENT TASKに「Canoviaが確認できた事実」として最近のEvidenceを最大3件表示します。',
            'AI演習・制作ファイル・集中作業を同じTask Evidence基盤へ集約し、将来のGitHub・ファイル・写真・Calendar連携へつなげます。',
        ],
        'tip' => 'Evidenceは「作業した事実」と「進捗を変える根拠」を分けて扱います。集中時間だけで進捗が上がることはありません。',
    ],
    [
        'version' => 'v41.0',
        'date' => '2026-09-24',
        'title' => '時間ではなく、前進した証拠を中心に',
        'summary' => 'HomeのPlanタブを日常利用用Plan Hubへ再設計し、Focus Timerを任意Toolへ変更。AI演習を最初のTask Evidenceとして自動記録できる基盤を追加しました。',
        'highlights' => [
            'HomeのPlanタブから大きなRoadmap再表示を外し、Plan概要・CURRENT TASK・Task短縮一覧・Plan Tools・最近の活動を直接確認できるようにしました。',
            'TaskのPrimary ActionはAI演習・制作ファイル・関連資料などTaskに合うToolを優先し、集中タイマーは必要なときだけ使う任意Actionに変更しました。',
            'estimated_minutes / remaining_minutesは進捗の証拠ではなく、Taskの重さや期限判断に使う「時間の目安」として扱います。',
            'TaskEvidence基盤を追加し、source / type / confidence / metadata / external_keyを持つ観測事実をidempotentに保存できます。',
            'AI演習の評価完了をnative Evidenceとして自動保存し、score・弱点・推奨進捗・next_stepをTaskへ紐付けます。',
            'ExecutionAdapter、EvidenceProgressService、TaskMilestoneを追加し、GitHub・ファイル・写真・Calendar・将来AIへ拡張できる境界を用意しました。',
        ],
        'tip' => '普段はPlanタブの「次に進めること」からそのTaskに合うToolを開いてください。時間を測りたいときだけ集中タイマーを使えます。',
    ],
    [
        'version' => 'v40.7.5',
        'date' => '2026-09-24',
        'title' => 'AI評価JSONの受け戻しをさらに安定化',
        'summary' => '回答済みの演習データがDBに残っているのにPHP Sessionだけ失われた場合でも、評価JSONをそのまま受け取れるようにしました。',
        'highlights' => [
            '評価JSONのPOST時にもStudyPracticeSessionのanswered状態から問題・回答・評価Promptを復元します。',
            '画面を一度GETし直さなくても、保存済みの回答状態から評価結果を学習履歴へ保存できます。',
            '復元対象は本人のPlan / Task / actorに紐づくansweredセッションだけに限定し、評価済みセッションを再オープンしません。',
            'V40.7.4のnext_step、Task反映確認、進捗を勝手に下げないルール、既存のattempt idempotencyを維持します。',
        ],
        'tip' => '評価JSONを貼り付けたときに画面状態が一時的に失われても、回答済みデータが保存されていればそのまま評価へ進めます。',
    ],
    [
        'version' => 'v40.7.4',
        'date' => '2026-09-24',
        'title' => 'AI演習を「次にやること」まで一本道に',
        'summary' => '回答・AI評価・結果を同じ長い画面へ積み上げる構成をやめ、現在のStepだけを主役にしながら、評価後は次の学習Actionへそのまま進めるようにしました。',
        'highlights' => [
            'AI演習の上部に「問題準備 → 回答 → AI評価 → 結果・次Action」の進行状況を追加しました。',
            '回答完了後は問題を折りたたみ、AI評価中は評価の受け渡しだけを主表示します。評価後は結果を画面上部へ出し、過去Stepは必要なときだけ確認できます。',
            '評価AIへnext_stepを必ず返すよう依頼し、practice / review / continue_task / complete_task / plan_updateの5種類へ正規化します。',
            '次の演習が必要な場合は、重点分野と問題数を前回の評価から次のPractice Strategyへ引き継ぎます。',
            '結果をTaskへ反映した後、「この内容で次の演習へ」から弱点補強をそのまま続けられます。',
        ],
        'tip' => 'AI演習では、画面の一番目立つActionだけを順番に進めれば、評価後の次の学習までたどり着けます。',
    ],
    [
        'version' => 'v40.7.3',
        'date' => '2026-09-24',
        'title' => 'AI演習の結果表示と画面遷移を安定化',
        'summary' => 'AI演習で評価JSONを読み込んだ後に結果が消えたり、画面が変わっていないように見える問題を修正しました。',
        'highlights' => [
            'PWAのNavigation PreloadがAI演習などの通常画面へ二重GETを発生させていたため、registration-wideのpreloadを無効化しました。',
            'AI演習の回答済み・評価済み状態をStudyPracticeSessionとStudyPracticeAttemptから復元し、再読み込みやPHP Session競合でも結果を失いにくくしました。',
            '評価JSONの読み込み後は評価結果へ、問題JSONの読み込み後は問題欄へ自動で移動し、次に何が起きたか分かるようにしました。',
            '評価前の外部AI handoffも、保存済みの問題・途中回答・評価Promptから静かに復元できます。',
            'AI演習・認証・管理画面などInstant Start対象外の画面は、今後1回の通常GETだけで処理されます。',
        ],
        'tip' => '評価JSONをCanoviaへ戻したら、そのまま評価結果まで移動します。再読み込みしても未反映の評価結果を復元できます。',
    ],
    [
        'version' => 'v40.7.2',
        'date' => '2026-09-24',
        'title' => '初期計画のAI受け渡し画面を刷新',
        'summary' => '計画作成時だけ残っていた大きなPrompt・JSON入力欄を整理し、他のAI支援と同じワンタップ中心の受け渡しUIへ統一しました。',
        'highlights' => [
            '初期計画の相談Promptは通常画面から隠し、「相談文をコピー」を主操作にしました。',
            'AIの回答は「クリップボードから貼り付けて読み込む」で貼り付けと送信を1操作にまとめました。',
            'PromptやJSONの原文は必要な場合だけ詳細表示から確認・手動操作できます。',
            'JSONエラー時の修正依頼も大きなテキスト欄を表示せず、コピー操作と内容概要を中心に整理しました。',
            'AI演習・計画更新・資料整理と同じAI Handoffの見た目と操作感へ統一しました。',
        ],
        'tip' => '計画作成では、相談文をAIへ送り、返ってきた回答をコピーしてCanoviaの貼り付けボタンを押すだけで進められます。',
    ],
    [
        'version' => 'v40.7.1',
        'date' => '2026-09-24',
        'title' => 'AI演習の途中回答を自動保存',
        'summary' => 'AI演習の回答を入力中から自動保存し、画面を離れたりブラウザを閉じたりしても、同じ演習を開けばそのまま途中から続けられるようにしました。',
        'highlights' => [
            '回答欄を編集するたびに端末へ即時保存し、短い間隔でStudyPracticeSessionにも自動保存します。',
            '保存ボタンや「再開しますか？」の確認は追加せず、AI演習を開き直すだけで途中回答を復元します。',
            'PHP Sessionが失われても、未完了のStudyPracticeSessionに問題と途中回答が残っていれば自動的に復元します。',
            '画面を閉じる直前にも保存を試み、通信が間に合わない場合は端末内の下書きから次回復元します。',
            '「演習をやり直す」を選んだ場合は現在のSessionをabandonedとして扱い、古い途中回答を自動再開しません。',
        ],
        'tip' => 'AI演習は途中で閉じても大丈夫です。特別な保存操作をせず、そのまま別の画面へ移動できます。',
    ],
    [
        'version' => 'v40.7',
        'date' => '2026-09-23',
        'title' => 'Canovia Futureで次の進化に参加',
        'summary' => 'フィードバック入口をCanovia Futureへ広げ、Canoviaが検討している将来候補をSupportできるようにしました。',
        'highlights' => [
            'フィードバックからCanovia Futureを開き、将来候補のSupport数と現在のstatusを確認できます。',
            '同じactorから同じ候補へのSupportは1件に保ち、Supportはいつでも取り消せます。',
            '500 Supportは実装確約ではなく、Roadmap入り・正式検討を始める目安として扱います。',
            '従来の自由記述Feedbackは「その他のフィードバック」として引き続き利用できます。',
            'Entitlementとは別に、将来の段階公開へ拡張できる最小Feature Flag境界を追加しました。',
        ],
        'tip' => '気になる候補だけSupportしてください。Support数はCanoviaの優先順位を考える材料として使われます。',
    ],
    [
        'version' => 'v40.6',
        'date' => '2026-09-23',
        'title' => '将来の収益化に備えるEntitlement基盤',
        'summary' => '現在の無料利用を変えずに、Premium・Coin・Gift・Sponsorなど複数の経路から同じ機能利用権を解決できる共通Access境界を追加しました。',
        'highlights' => [
            'Feature Keyを一元管理し、AI Practice・Question Pack・Project Artifactなどを安定した識別子で扱えるようにしました。',
            'FeatureAccessServiceを追加し、機能側がPremiumやCoinを直接判定せず「このactorはこのFeatureを使えるか」だけ問い合わせる構造にしました。',
            '現在はFreeEntitlementResolverだけを登録し、全Featureを従来どおり無料で利用できます。',
            'Premium / Coin / Gift / Sponsorはaccess sourceとして予約しましたが、購入・残高・消費・付与・課金UIはまだ実装していません。',
            'AI演習とProject ArtifactのRoute、Home/Plan上のTool表示を共通Access境界へ接続しました。',
            'Question PackはAI Practiceとは別Featureとして判定でき、将来利用権が異なる場合は外部AI providerへフォールバックできる構造にしました。',
            'Feature Flagは機能公開、Entitlementはactorの利用権として責務を分離しています。',
            'AccessDecisionは将来BehaviorEventへ安全な判定メタデータを接続できる形にしましたが、現時点ではアクセス判定ログを増やしていません。',
        ],
        'tip' => 'V40.6では課金制限は有効になっていません。今まで使えていた機能はそのまま利用できます。',
    ],
    [
        'version' => 'v40.5',
        'date' => '2026-09-23',
        'title' => 'Canovia Guideで「やりたいこと」から案内',
        'summary' => 'ヘッダーから開ける検索式Guideリストと、実際の画面を光らせながら案内するSpotlightチュートリアル基盤を追加しました。',
        'highlights' => [
            'モバイルでは更新情報の左、デスクトップではヘッダーにCanovia Guideの入口を追加しました。',
            'Guideは種類ごとに折りたたみ、＋/−で開閉でき、上部検索から目的を直接探せます。',
            '実際のCanovia画面をSpotlight表示し、対象ボタンを押しながら複数画面にまたがって案内できます。',
            'Guideの現在Stepと完了状態を端末内に保存し、画面遷移後も自動で続きます。',
            '初期Guideとして計画作成、今日やること、タイマー、計画更新、AI演習、関連資料を収録しました。',
            '共同計画カテゴリを用意し、「共同計画を作って招待する」「共同計画に参加する」を最初から収録しました。',
            '将来の実績機能などからdata-guide-startまたはCanoviaGuide.start(key)だけで同じGuide Runnerを起動できます。',
        ],
        'tip' => '機能名が分からなくても、ガイドで「共同計画」「AI演習」「タイマー」などやりたいことを検索できます。',
    ],
    [
        'version' => 'v40.4.3',
        'date' => '2026-09-23',
        'title' => '外部AIとの受け渡しUIを全体で統一',
        'summary' => 'AI演習だけでなく、計画更新・方針変更・AIコンテキスト共有・Resource整理でもRaw Prompt / JSONを通常画面から外し、コピー&ペースト操作を短くしました。',
        'highlights' => [
            '計画更新画面の巨大Prompt textareaとJSON textareaを通常表示から外しました。',
            'Promptは「含まれる情報」を折りたたみで確認し、原文は1クリックでコピーできます。',
            '更新JSON・方針変更JSON・Resource割当JSONは、クリップボードから1クリックで貼り付けて確認へ進めます。',
            'Clipboard読取りに対応しない場合だけ手動貼り付け欄を自動展開します。',
            'JSONエラー時の修正PromptもRaw本文を大きく表示せず、コピーと内容要約を中心にしました。',
            '方針変更の専用画面とチャット画面、AIコンテキスト共有、Resource整理も同じ視覚ルールへ統一しました。',
            'HomeのUniversal AI importは既に折りたたみ式のため現状を維持します。',
        ],
        'tip' => '外部AIとの往復では、基本的に「コピー」→AIへ送信→AI側で返答をコピー→「クリップボードから貼り付け」の操作だけで進められます。',
    ],
    [
        'version' => 'v40.4.2',
        'date' => '2026-09-23',
        'title' => 'Home見出しの手書き感と余白を整理',
        'summary' => 'Homeの主要見出しでZen Kurenaido本来の筆記感が出るよう極太指定を抑え、モバイルではキャラ吹き出しを非表示にして本文との競合をなくしました。',
        'highlights' => [
            '「今日も、あなたのペースで。」「今日やること」などHomeの主要見出しをZen Kurenaidoの自然な400ウェイトで表示します。',
            'コンポーネント側のfont-weight 800〜850による擬似太字を見出しでは上書きし、手書き感が潰れないようにしました。',
            '本文・説明・ボタン・補助情報は引き続きKlee Oneのままです。',
            'モバイルHomeではマスコットの吹き出しを非表示にし、見出しや本文へ重ならない構成にしました。',
            'デスクトップでは横幅に余裕があるため、マスコット吹き出しを維持します。',
        ],
        'tip' => '短い見出しは手書き感を強く、長く読む情報は今までの読みやすさを維持する二層構成です。',
    ],
    [
        'version' => 'v40.4',
        'date' => '2026-09-23',
        'title' => 'Canoviaの文字とAI受け渡しを軽やかに',
        'summary' => '世界観を感じられる手書き調フォントを試験導入し、AI演習のPrompt・JSON原文を通常画面から隠してコピー&ペースト操作を短くしました。',
        'highlights' => [
            '本文・説明・ボタンはKlee Oneで読みやすさを保ち、ヘッダーやTask名など短い見出しだけZen Kurenaidoで手書き感を強めました。',
            'Webフォントを取得できない環境ではKlee One・游教科書系・システムフォントへ自動フォールバックします。',
            'コード・JSONなど機械的に読む情報は従来どおり等幅フォントを維持します。',
            'AI演習では巨大なPrompt原文を通常表示せず、「含まれる情報」だけ必要時に折りたたみで確認できます。',
            '問題JSON・評価JSONはクリップボードから1クリックで貼り付け、そのまま読み込み・確認へ進めます。',
            'クリップボード読取りに対応しないブラウザでは、手動貼り付け欄を自動で開いて従来操作へ安全に戻ります。',
            'JSONエラー時の修正Promptも原文を大きく表示せず、コピー操作と内容要約を中心にしました。',
        ],
        'tip' => '通常は「Promptをコピー」→AIへ送信→AI側で返答をコピー→「クリップボードから貼り付け」の流れだけで進められます。',
    ],
    [
        'version' => 'v40.3.1',
        'date' => '2026-09-23',
        'title' => 'AP問題集の文脈品質と弱点Coverageを強化',
        'summary' => '類題で元問題の自然な文脈を壊さない制作ルールを追加し、AP科目A Canovia Coreを74問へ拡張しました。',
        'highlights' => [
            '過去問・定番問題を参考にする場合、意味領域・業務文脈・専門用語を不自然に抽象化しないContent Quality Rules v1.1を追加しました。',
            '外部AIの問題生成Promptにも同じルールを適用し、病気の検査を「異常な対象」のような人工的な表現へ一般化しないよう明示しました。',
            'AP科目A Canovia Coreを28問から74問へ拡張し、ベイズ・MIPS・ボトルネック・ラウンドロビン・スタベーション・可用性・品質特性などを追加しました。',
            '現在のTaskで重点となる主要弱点は、単独FocusでもQuestion Bankへ切り替えられるよう各3問以上のCoverageを確保しました。',
            'MTU計算Focusが単なる「計算」タグの問題まで拾っていた部分一致を修正し、具体的な弱点名を優先してCoverageを判定します。',
            'アルゴリズム、テスト、CI、Webセキュリティ、PKI、マネジメント、ストラテジ、仮想化、RAID、SQLなど科目A横断演習向けの範囲も追加しました。',
        ],
        'tip' => '類題は数値だけ変えるのではなく、本番で自然な状況設定と用語を保ったまま解く練習として使えるようにしています。',
    ],
    [
        'version' => 'v40.3',
        'date' => '2026-09-23',
        'title' => 'AP科目AのCanovia問題集を同梱',
        'summary' => '応用情報技術者試験の科目A向けに、IPA過去問の出題テーマを参考にしたCanovia Core v1を追加し、AdminからワンクリックでDraftへ取り込めるようにしました。',
        'highlights' => [
            'AP科目A向けのCanoviaオリジナル・類題を28問同梱しました。',
            'MTU計算・DNSレコードは単独弱点でもQuestion Bank Coverageを満たせるよう、それぞれ3問以上を用意しました。',
            'ネットワーク・DB・計算・OS・セキュリティを中心に、現在の弱点補強へ使えるlearning_metadataを設定しました。',
            'IPA過去問を参考にした類題はderivedとして出典を保持し、Canovia独自問題はcanovia_originalとして区別します。',
            'AdminのQuestion Pack画面へBundled Pack一覧とDraft取込ボタンを追加しました。',
            '公式試験の解答記号をそのまま保持できるよう、choice.idでア・イ・ウ・エなどUnicode文字を利用可能にしました。',
        ],
        'tip' => 'Admin > 問題集から「応用情報技術者試験 科目A Canovia Core v1」をDraftへ取り込み、内容確認後にpublishedへ変更するとAI演習で自動利用されます。',
    ],
    [
        'version' => 'v40.2',
        'date' => '2026-09-22',
        'title' => 'Canovia問題集から直接演習',
        'summary' => '公開Question Packで十分にカバーできるTaskは外部AIへのコピペなしで直接出題し、選択・複数選択・数値問題はCanovia側で機械採点できるようにしました。',
        'highlights' => [
            'Question BankのCoverageをPlan・Task・資格コード・重点分野から判定し、十分な場合だけQuestion Bank Providerを自動選択します。',
            '問題数や重点分野のCoverageが不足する場合は、従来どおり外部AIへ安全にフォールバックします。',
            'exact_choice・exact_multiple・numeric_toleranceのgrading_ruleをCanovia側で機械採点します。',
            '任意の思考過程をユーザーが入力した場合やai_rubric問題は、Question Bankの正答・rubricを評価根拠として外部AIへ渡します。',
            'AdminへQuestion Pack JSONのDraft取込・公開状態管理を追加し、公開済みPackは上書き不可のversion運用にしました。',
            '問題ごとのsource_type・source_referenceを保持し、Question Bank出題時は出典を画面で確認できます。',
        ],
        'tip' => 'Question Packが対応済みならAI演習から「演習を始める」だけで問題へ進めます。未対応・Coverage不足の範囲だけ外部AIを使います。',
    ],
    [
        'version' => 'v40.1',
        'date' => '2026-09-22',
        'title' => 'AI演習の選定と評価をCanoviaが統括',
        'summary' => '外部AIを使う現在の操作は増やさず、Canoviaが演習方針・問題Provider・評価Provider・演習Sessionを一貫して管理する構造へ進化しました。',
        'highlights' => [
            'Taskと過去の学習履歴から、初回理解度確認・弱点補強・定着応用・Task定着確認の演習方針をCanoviaが決めます。',
            '現在は外部AIへ問題準備と評価を引き継ぎますが、Question Bankや内蔵AIへ切り替えるProvider Routerを追加しました。',
            '外部AIへ渡すPromptにCanoviaが決めた演習方針・重点分野・問題数目安を含め、AI側で別方針へ置き換えないようにしました。',
            '1回の演習をStudyPracticeSessionとして追跡し、ready・answered・assessed・completed・abandonedの状態を保存します。',
            '問題選定時の学習Context、Provider、選ばれた問題参照、評価Providerを保存し、将来の選定精度検証に使える土台を作りました。',
        ],
        'tip' => '今まで通りAI演習を開いて使えます。現在の外部AIとの受け渡しは、将来Canovia内で自動化できる構造になっています。',
    ],
    [
        'version' => 'v40.0',
        'date' => '2026-09-22',
        'title' => 'AI演習を学習基盤へ',
        'summary' => 'AIが問題を作るだけの演習から、回答形式・問題単位の学習分析・自動Plan優先度・Question Bankを分離して扱えるLearning Coreへ拡張しました。',
        'highlights' => [
            '1問に選択肢・数値・短文・記述・思考過程など複数の回答欄を組み合わせられるresponse_fieldsを追加しました。',
            '旧type / choices形式はCanovia側で新形式へ自動変換し、既存AI演習との互換性を維持します。',
            '評価JSONで問題ごとの正誤・フィードバック・思考過程フィードバック・誤解ポイントを保存・表示できるようにしました。',
            'Plan優先度をAuto / Manualへ分離し、Autoでは期限・進捗差・残作業量・利用可能時間・停滞からCanoviaが内部評価します。',
            'Resource ToolでTask資料をPlan資料と二重カウントしていた問題を修正し、Task関連件数とPlan全体件数を分けて表示します。',
            '資格別Question Packを将来配信できるよう、問題ソース・回答Schema・採点Rule・学習Metadataを分離したQuestion Bank基盤を追加しました。',
        ],
        'tip' => 'Plan優先度はCanoviaに任せることも、重要な計画だけ手動で固定することもできます。',
    ],
    [
        'version' => 'v39.7',
        'date' => '2026-09-21',
        'title' => 'AI JSONの崩れをCanovia側で吸収',
        'summary' => '生成AIへ修正を何度も依頼しなくても済むよう、意味を変えずに機械的に直せるJSONの構文崩れをCanovia共通層で自動補正するようにしました。',
        'highlights' => [
            'JSON構造として使われたスマートクォート（“ ”）を半角ダブルクォートへ自動補正します。',
            '文字列の外にある全角のコロン・カンマ・波括弧・角括弧・全角空白をJSON記号へ自動補正します。',
            '問題文や説明文の中にある“ゼロトラスト”や「A，B：C」のような本文表現は変更しません。',
            '末尾カンマ・コメント・コードブロック・文字列内改行など既存の安全補正と同じ共通Normalizerで処理します。',
            'Canoviaで安全に直せない場合だけ、V39.6のAI修正依頼へフォールバックします。',
        ],
        'tip' => '軽微なJSON崩れはそのまま貼り付けて大丈夫です。Canoviaが安全に直せる範囲を先に吸収します。',
    ],
    [
        'version' => 'v39.6',
        'date' => '2026-09-21',
        'title' => 'AI演習のJSONエラーからその場で復旧',
        'summary' => 'AI演習で問題JSONや評価JSONを読み込めなかったとき、エラー表示だけで止まらず、元のPromptと正しいPlan・Task IDを含む修正依頼をその場でコピーできるようにしました。',
        'highlights' => [
            '問題JSONの構文・形式エラー時に、失敗したJSON・Canoviaのエラー・元の問題作成Promptをまとめた修正依頼を表示します。',
            '評価JSONでも同じ復旧ループを使え、元の評価Promptと採点内容をできるだけ保持した修正をAIへ依頼できます。',
            '修正依頼には正しいtarget_plan.idとtarget_task.idを明記し、AIが別IDを推測しないようにしています。',
            '長い修正Promptはtextarea本体からコピーする方式にし、巨大なHTML属性へ同じPromptを複製しないようにしました。',
        ],
        'tip' => 'JSONエラーが出たら「修正依頼をコピー」を押して、JSONを作った同じAIへそのまま送ってください。',
    ],
    [
        'version' => 'v39.5',
        'date' => '2026-09-21',
        'title' => '今日やることを優先順位から決める',
        'summary' => 'Homeの「今日のおすすめ」をGuidance Deckへ変更し、何をやるかはPlan/Taskの優先順位、どう進めるかはCanoviaの行動適応提案という役割に分離しました。',
        'highlights' => [
            'Planに1〜5の計画優先度を追加し、1を最優先としてHomeの表示順に使用します。',
            '各PlanからTask priority、進行中、sort orderの順で次Taskを客観的に1件選びます。',
            '期限・行動状態・始めやすさなどのRecommendationServiceはTask選定に使わず、選定済みTaskの推奨時間と理由だけを提案します。',
            'Planごとのカードを横スワイプでき、最優先Planを先頭にしながら他Planの次Taskも確認できます。',
            'AI演習や制作ファイルなど、そのTaskに合うCanovia Toolがある場合はカード内から直接開けます。',
        ],
        'tip' => 'Plan編集の「計画優先度」で、今いちばん優先したい目標を1に設定できます。',
    ],
    [
        'version' => 'v39.4',
        'date' => '2026-09-21',
        'title' => 'Canovia Toolsへの入口を分かりやすく',
        'summary' => '資格学習PlanではAI演習へPlan詳細の最上部から直接入れるようにし、カテゴリ設定が原因で使えない場合も理由が分かるようにしました。',
        'highlights' => [
            '資格学習Planの未完了TaskにAI演習が使える場合、Plan詳細上部へ「AI演習」ボタンを表示します。',
            'Canovia Toolsセクションへ直接移動できるアンカーを追加しました。',
            '資格・試験・学習に見えるPlanでカテゴリが資格学習ではない場合、AI演習が出ない理由とカテゴリ確認導線を表示します。',
            'AI演習の利用条件そのものは変更せず、誤って他カテゴリへ自動適用しない設計を維持しています。',
        ],
        'tip' => 'APなどの資格学習Planでは、Plan詳細を開いたら上部の「AI演習」からすぐ問題生成へ進めます。',
    ],
    [
        'version' => 'v39.3',
        'date' => '2026-09-21',
        'title' => 'AI演習を学習成果へつなげる',
        'summary' => 'AI演習の評価を学習履歴として残し、確認後にTaskの進捗・評価根拠・次のActionへ安全に反映できるようにしました。',
        'highlights' => [
            'AI演習の問題・回答・評価・正答率・強み・弱点を学習履歴として保存します。',
            '評価プレビューを確認して「Taskへ反映」を押した場合だけ、Task進捗・進捗根拠・次のActionを更新します。',
            '同じ評価JSONはrequest_hashで1件へ収束し、反映ボタンを再送しても二重反映しません。',
            'AI演習だけを理由に既存のTask進捗を下げず、現在値とAI提案の高い方を採用します。',
            '最近の演習結果と弱点を次回の問題生成Promptへ渡し、同じTaskで弱点補強を続けられます。',
        ],
        'tip' => 'AI演習で見つかった弱点は、次の演習問題へ自動で引き継がれます。評価を確認してからTaskへ反映してください。',
    ],
    [
        'version' => 'v39.2',
        'date' => '2026-09-21',
        'title' => '作業に合わせてCanovia Toolsを使えるように',
        'summary' => 'Taskを進めるときにタイマーだけでなく、AI演習・関連資料・制作ファイルなど、その計画に合う道具へそのまま進める基盤を追加しました。',
        'highlights' => [
            'Plan詳細にCanovia Toolsを追加し、現在のおすすめTaskに使える道具をまとめて表示します。',
            '資格学習カテゴリではAI演習を利用でき、AIが作った問題JSONをCanoviaの回答UIへ読み込めます。',
            'AI演習の回答後は問題と回答を含む評価用プロンプトを自動生成し、AIの評価JSONをCanoviaでプレビューできます。',
            '既存のタイマー・関連資料・制作ファイルも同じTool体系へまとめ、Taskから自然に使えるようにしました。',
            'AI演習MVPでは評価結果を自動で進捗へ反映せず、確認可能なプレビューまでに留めて安全性を優先しています。',
        ],
        'tip' => '資格学習PlanのTaskを開くと「AI演習」が表示されます。問題作成から回答・評価確認まで、Taskの文脈を保ったまま進められます。',
    ],
    [
        'version' => 'v39.1',
        'date' => '2026-09-21',
        'title' => 'Instant Startを安全に復活',
        'summary' => 'V39で安定化したオンライン操作を変えず、Renderの起動待ち中だけ端末内のホーム・今日・ロードマップを先に表示できるようにしました。',
        'highlights' => [
            'Service WorkerはGETナビゲーションだけを扱い、POST・PUT・PATCH・DELETEなどの更新操作には介入しません。',
            'Instant Start対象をホーム・今日・ロードマップの3画面に限定し、AI JSON・計画更新・認証・管理画面は従来どおり通常通信で処理します。',
            'PWA初回起動のhandoffはService Worker対象外とし、V39で安定化したログイン・Guest計画の引き継ぎを維持します。',
            'サーバーが休止している可能性が高い場合はoffline shellを即表示し、裏ではGETリクエストと/health確認だけで復帰を待ちます。',
            'サーバー復帰後は_canovia_network付きのnetwork-only遷移で本画面へ戻し、offline shellへのループを防ぎます。',
        ],
        'tip' => 'ホーム画面版Canoviaをしばらく使っていなかった後でも、前回同期した状態を先に確認できます。更新操作は接続後の通常画面で行われます。',
    ],
    [
        'version' => 'v39.0',
        'date' => '2026-09-21',
        'title' => '多重実行とPWA起動を安定化',
        'summary' => '通信や画面遷移が遅いときでも、成功済みの操作をもう一度実行してデータが重複しないよう、重要な変更操作を再送に強くしました。',
        'highlights' => [
            '計画作成に作成リクエストIDを持たせ、同じ送信が再度届いても新しい計画を増やさず元の計画へ戻します。',
            '初期計画JSONは内容のハッシュで反映済みか判定し、同じJSONの再送でタスク一式が二重登録されないようにしました。',
            '計画更新の確定も提案トークンを永続的な反映キーとして記録し、成功後の再送を重複更新として実行しません。',
            '作業タイマー開始は利用者単位で直列化し、ダブルタップや同時リクエストでも進行中タイマーを1件に保ちます。',
            '重要な送信フォームは処理中の再送を画面側でも抑止し、PWAや低速通信での連打を防ぎます。',
            '通常のPWA manifest取得では引き継ぎトークンを発行せず、インストール時だけ初回起動用トークンを使う構成へ変更しました。',
            'iOSのHEAD確認ではPWA引き継ぎトークンを消費せず、使用済みの起動URLが残っていても静かにホームへ戻るようにしました。',
        ],
        'tip' => '通信が遅く見えても、同じ操作を繰り返したときに計画・タスク・タイマーが増殖しないことを優先した安定化アップデートです。',
    ],
    [
        'version' => 'v38.9',
        'date' => '2026-09-21',
        'title' => '管理画面と計画作成を整理',
        'summary' => '増えてきた運営機能をひとつの入口へまとめ、初回の計画作成も次に何をするか分かりやすい画面へ整えました。',
        'highlights' => [
            '管理パスワード入力後に運営ダッシュボードを表示し、フィードバックと計画作成・更新の診断へUIから移動できるようにしました。',
            'フィードバック・診断画面に共通の管理ナビを追加し、個別URLを覚えなくても行き来できます。',
            '管理画面の入口を /admin に統一し、従来の /admin/feedback/login は互換用として残しています。',
            '計画作成画面を「基本情報 → AIで具体化」の2段階が一目で分かる構成へ整理しました。',
            '計画名を最重要入力として強調し、期限・詳細設定・未来メモ・作成後の流れを整理してスマホでも追いやすくしました。',
        ],
        'tip' => '計画作成では目標名だけでも大丈夫です。作成後にAIへ進み、タスクや順番を具体化できます。',
    ],
    [
        'version' => 'v38.8',
        'date' => '2026-09-21',
        'title' => '計画作成・更新の診断を強化',
        'summary' => '初期離脱やJSONエラーを推測ではなく確認できるよう、計画作成・更新の各段階を匿名性に配慮して記録する診断基盤を追加しました。',
        'highlights' => [
            '初期計画の画面到達、プロンプトコピー、JSON読み込み試行・成功・失敗を段階別に記録します。',
            '計画更新のプロンプト生成、JSONプレビュー、更新確定までを段階別に記録します。',
            'Web/PWAとPC/モバイルを区別して集計し、端末固有の不具合を見つけやすくしました。',
            '失敗時はJSON本文やプロンプトを保存せず、invalid_json・wrong_planなど診断用の理由コードだけを残します。',
            '管理画面に7日/30日のファネル、成功率、利用環境、直近の失敗を確認できる診断ページを追加しました。',
            '診断記録がDBへ保存できない場合でも本体機能を止めず、Renderログへ安全な集計情報を残します。',
        ],
        'tip' => '管理画面の「計画作成・更新の診断」から、どの段階で利用者が止まっているか確認できます。',
    ],
    [
        'version' => 'v38.7',
        'date' => '2026-09-20',
        'title' => '初期計画JSONの読み込みを安定化',
        'summary' => '計画作成時のJSONだけ別の厳しい判定が残っていた問題を修正し、PC・スマホで同じサーバー側判定を使うよう統一しました。',
        'highlights' => [
            '初期計画のJSON送信をブラウザ本来のPOSTへ統一し、端末側JavaScriptが送信を止めないようにしました。',
            '対象計画はplan IDを安全性の基準とし、タイトル表記のわずかな差で「別の計画」と誤判定しないよう改善しました。',
            'priorityを実行順として6以上で出力するAI回答を、Canovia側で1〜5へ安全に補正します。',
            'actions・changes・tasks・camelCase・create_taskなど、初期計画で起きやすい形式差もCanovia側で吸収します。',
            'JSONエラーはPC・PWAともにCanoviaサポーターのチャット形式で表示し、元の相談プロンプトを含む修正依頼をコピーできます。',
            'スマホの初期計画画面で見出しサイズと下部余白を調整し、固定ナビとの重なりを軽減しました。',
        ],
        'tip' => '軽微なJSON形式差はCanoviaが自動調整します。別のplan IDが明示されている場合だけ、安全のため処理を止めます。',
    ],
    [
        'version' => 'v38.6',
        'date' => '2026-09-20',
        'title' => 'JSONの揺れをCanovia側で吸収',
        'summary' => 'AIへ何度も修正を頼まなくても済むよう、よくあるJSON形式の違いをCanovia側で安全に補正する互換レイヤーを追加しました。',
        'highlights' => [
            'actions・changes・updates・tasksなど、operations以外の一般的な配列名をCanovia形式へ変換します。',
            'camelCaseのキー、操作typeの別名、status表記などをCanovia側で正規化します。',
            '計画更新画面では現在開いている計画を正としてtarget_plan・flow・schema_versionを安全に補正します。',
            '既存タスクIDが欠けていても、タスク名が一意に一致する場合はCanovia側でtask_idを補完します。',
            '補正した内容はプレビュー上の「自動調整」として表示し、意味を勝手に変更する補正は行いません。',
            'AI用プロンプトへ出力直前の8項目セルフチェックを追加しました。',
        ],
        'tip' => '軽微な形式差はCanoviaが吸収します。意味や対象タスクを安全に判断できない場合だけエラーとして止めます。',
    ],
    [
        'version' => 'v38.5',
        'date' => '2026-09-20',
        'title' => 'JSON修正ループを改善',
        'summary' => 'エラー修正をAIへ依頼しても再エラーになるケースに対し、修正依頼へ元の仕様・正しい計画ID・タスクIDを含めるよう改善しました。',
        'highlights' => [
            '計画更新のJSON解析を共通AiJsonInputNormalizerへ直接統一し、旧JSON抽出処理との二重基準をなくしました。',
            'JSONエラーの修正依頼へ、元のCanoviaプロンプトと正しい計画・タスクIDを含めるようにしました。',
            '構文エラーと、構文は正しいがCanoviaの条件に合わないエラーを表示上で区別します。',
            'AIに存在しないtask_idを推測させず、Canoviaが渡したIDだけを使って修正するよう指示を強化しました。',
        ],
        'tip' => '修正依頼をコピーして、最初にJSONを作ったAIへ送ってください。返ってきたJSONだけを同じ入力欄へ貼り直します。',
    ],
    [
        'version' => 'v38.4',
        'date' => '2026-09-20',
        'title' => '安定性を優先した一時調整',
        'summary' => '計画更新の確実性を優先するため、Instant StartとService Worker更新機構を一時停止し、通常のオンライン動作へ戻しました。',
        'highlights' => [
            'Service Workerによる画面差し替えとInstant Startを一時停止しました。',
            '既存のCanovia/PaceKeeper用Service Workerとシェルキャッシュを自動で解除・整理します。',
            '「Canoviaを更新できます」の更新バナーを一時的に停止しました。',
            '計画更新のJSONはクライアント側で送信を止めず、Laravel側で正規化・検証する通常POSTへ一本化しました。',
            'JSON構文エラーは、Canoviaサポーターのチャット形式で修正依頼を案内します。',
        ],
        'tip' => 'まず計画更新などのコア機能を安定させ、その確認後にInstant Startを再設計して戻します。',
    ],
    [
        'version' => 'v38.3',
        'date' => '2026-09-20',
        'title' => '計画更新とPWA更新を再修正',
        'summary' => 'JSONから計画変更を読み込めない問題と、「更新する」を押しても切り替わったことが分かりにくい問題を再調査して修正しました。',
        'highlights' => [
            '計画更新のJSON読み込みはJavaScriptで再送せず、ブラウザ本来のPOST→保存→リダイレクトへ一本化しました。',
            'JSONプレビュー用フォームを非同期送信の対象から完全に外し、Safari/PWAでもサーバーへ確実に届く構成にしました。',
            'PWA更新時は新しいService Workerが有効化されたあと、開いているCanovia画面を最新バージョンへ再ナビゲートします。',
            '更新完了後に「Canoviaを最新バージョンへ更新しました」と表示し、切り替わったことを確認できるようにしました。',
        ],
        'tip' => '計画更新ではJSONを貼り付けて「変更内容を読み込んで確認」を押すと、次の画面で反映前プレビューが表示されます。',
    ],
    [
        'version' => 'v38.2',
        'date' => '2026-09-20',
        'title' => 'PWA更新と読み込み画面を改善',
        'summary' => '「更新する」を押しても反映されないことがある問題を直し、読み込み中の作業目安が全計画の合計だと分かるようにしました。',
        'highlights' => [
            '「Canoviaを更新できます」から更新した際、新しいService Workerへ切り替わったあと確実に再読み込みするよう改善しました。',
            'iOS/PWAで更新イベントを取りこぼした場合にも、数秒後に最新画面へ切り替えるフォールバックを追加しました。',
            '読み込み画面の「今日の目安」を「全計画の今日の目安」と明示しました。',
            '前回同期時点であることと、計画ごとの今日の目安時間を読み込み画面に表示します。',
        ],
        'tip' => '読み込み画面の時間は全計画の合計です。各計画の行を見ると、その計画だけの今日の目安も確認できます。',
    ],
    [
        'version' => 'v38',
        'date' => '2026-09-19',
        'title' => 'AI JSONの読み込みを安定化',
        'summary' => 'AIの回答に説明文やコードブロックが混ざっても読み取りやすくし、エラー時に次の行動が分かるよう改善しました。',
        'highlights' => [
            'AI JSONの読み取り処理を共通化し、前後の説明文・JSONコードブロック・末尾カンマなどを安全な範囲で吸収します。',
            'JSONを読み込めない場合は、Canoviaサポーターがチャット形式で原因と次の行動を案内します。',
            'エラー内容と元のJSONを含む修正依頼をワンタップでコピーし、使っていたAIへそのまま送れます。',
            '計画更新のプロンプト生成で二重送信が起きる経路を遮断し、成功後はページ全体を再読み込みせず会話部分だけ更新します。',
            'JSON読み込み後に入力欄だけ消えてプレビューへ進めない不具合を修正しました。',
        ],
        'tip' => 'JSONエラーが出たら「修正依頼をコピー」を押し、JSONを作ったAIへ送ってください。',
    ],
    [
        'version' => 'v37',
        'date' => '2026-09-19',
        'title' => 'タイマーを、もっと安心して使えるように',
        'summary' => '画面を閉じたまま時間が伸び続ける問題に対策し、復帰時に実際の作業状況を確認してから記録できるようにしました。',
        'highlights' => [
            'タイマー中に15分以上Canoviaを離れた場合、復帰時に「作業継続・休憩・離れた時点で終了・手動修正」から実際の状況を選べます。',
            '通常より長い作業時間は、終了時に確認を挟み、寝落ちや終了忘れをそのまま実績へ残しにくくしました。',
            'オフラインタイマーにも同じ考え方を適用し、再接続時の二重同期を防ぎながら補正内容を記録します。',
            '「今日」は開始前の00:00表示をやめ、別候補から同じおすすめが重複しないよう整理しました。',
            'ホームでは進行中の作業と今日のおすすめを優先し、モバイルのロードマップ操作や画面遷移時のローディング表示も整理しました。',
        ],
        'tip' => 'タイマー中に画面を閉じても、自動で作業終了とは判断しません。長く離れた場合は、戻ったときに実際の状況を選んでください。',
    ],
    [
        'version' => 'v33',
        'date' => '2026-09-17',
        'title' => '更新情報をもっと見やすく、声が届く形に',
        'summary' => '更新内容を最前面のカードで確認でき、フィードバックへの対応も更新情報として伝えられるようになりました。',
        'user_voice' => '「更新内容をもっと見やすくしたい」「送ったフィードバックが改善につながったことが分かると嬉しい」という声を受けて改善しました。',
        'feedback_linked' => true,
        'highlights' => [
            '更新情報の詳細を、一覧のさらに手前に出る専用カードで表示するようにしました。',
            '詳細カードは×・カード外クリック・Escキーで閉じられます。',
            '管理画面から、フィードバックへの対応を「ユーザーの声」と「今回の改善」に分けて更新情報として公開できます。',
            'Canoviaの正式テーマをダークに統一し、ライト・自動テーマの選択肢をいったん非表示にしました。',
        ],
        'tip' => 'ヘッダーの「更新情報」から、最近の改善とユーザーの声への対応を確認できます。',
    ],
    [
        'version' => 'v31',
        'date' => '2026-09-17',
        'title' => '未来メモでもっとあなた向けに',
        'summary' => 'やりたいことや、なりたい自分を残して、計画づくりに活かせるようになりました。',
        'highlights' => [
            '「未来メモ」に、やりたいこと・なりたい自分・気になっていることなどを保存できます。',
            '未来メモをAI用プロンプトへ含めて、計画作成や計画更新をより自分向けにできます。',
            '目標がまだ決まっていないときは、未来メモをもとにAIと方向を整理できます。',
            'ダークモードを標準にし、Canoviaの世界観に合わせて表示コントラストを整えました。',
        ],
        'tip' => 'ホームの「未来メモ」から、まず1つだけでも残しておくと、次の計画づくりで使えます。',
    ],
    [
        'version' => 'v30',
        'date' => '2026-09-17',
        'title' => 'PWAの起動をもっとスムーズに',
        'summary' => 'サーバーの起動待ち中でも、端末内のCanoviaを先に表示できるよう改善しました。',
        'highlights' => [
            'しばらくCanoviaを使っていなかった場合でも、保存済みの画面を先に表示します。',
            'ホーム・今日・ロードマップの前回同期内容を接続待ち中にも確認できます。',
            '接続待ち中でもタイマーの開始・一時停止・再開ができます。',
            'サーバー復帰時の不要な再読み込みを減らしました。',
        ],
        'tip' => 'ホーム画面に追加したCanoviaでも、そのまま利用できます。',
    ],
    [
        'version' => 'v29',
        'date' => '2026-09-17',
        'title' => 'PaceKeeperからCanoviaへ',
        'summary' => 'ブランド名やPWA表示などをCanoviaへ統一し、新しいURLへ移行できる準備を整えました。',
        'highlights' => [
            '画面やPWA、AI用プロンプトの名称をCanoviaへ統一しました。',
            '共有リンクや招待リンクをCanoviaの正式URLへ移せるようにしました。',
            '以前のURLからでも、できるだけ同じ場所へ移動できる互換処理を追加しました。',
        ],
        'tip' => '以前保存したリンクも引き続き使えるよう、移行期間の互換性を残しています。',
    ],
    [
        'version' => 'v28',
        'date' => '2026-09-17',
        'title' => '制作ファイル・成果物をまとめて管理',
        'summary' => '共同制作で作っているファイルや成果物を、タスクや担当者と一緒に管理できるようになりました。',
        'highlights' => [
            'Google Drive・OneDrive・GitHubなどの制作物リンクをまとめられます。',
            '制作物に担当者・バージョン・関連タスク・メモを設定できます。',
            '共同計画では、メンバーと最新版の制作物を共有できます。',
        ],
        'tip' => '「関連資料」は参考にするもの、「制作ファイル」は実際に作っているものとして使い分けると整理しやすくなります。',
    ],
];
